# Generated by Django 3.2.6 on 2021-10-05 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=400)),
                ('email', models.EmailField(max_length=50, null=True)),
                ('subject', models.CharField(max_length=500, null=True)),
                ('message', models.CharField(max_length=2000, null=True)),
            ],
        ),
    ]
